#!/usr/bin/env bash

# Copyright 2014-2019 Ray Holder
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

# tests are running from here
readonly __DIR__="$(cd "$(dirname "${0}")"; echo $(pwd))"

function file_should_exist () {
    local target=$1
    if [ ! -f "${target}" ]; then
        echo \"${target}\" file does not exist
        exit 1
    fi
}

function dir_should_exist () {
    local target=$1
    if [ ! -d "${target}" ]; then
        echo \"${target}\" directory does not exist
        exit 1
    fi
}

function test_init () {
    cd "${__DIR__}"
    source ./debinate --skip-main

    mkdir test_init
    cd test_init

    init
    dir_should_exist .debinate
    dir_should_exist .debinate/root
    file_should_exist .debinate/after_install.sh
    file_should_exist .debinate/before_remove.sh
    file_should_exist .debinate/depends
}

function cleanup () {
    cd "${__DIR__}"
    rm -rf test_init
}

trap cleanup EXIT

test_init
